"""create zone_configs table

Revision ID: zone_configs_005_create
Revises: violations_004_create
Create Date: 2026-06-07 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'zone_configs_005_create'
down_revision = 'violations_004_create'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=True),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_configs_camera_id'), 'zone_configs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_zone_configs_id'), 'zone_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_configs_id'), table_name='zone_configs')
    op.drop_index(op.f('ix_zone_configs_camera_id'), table_name='zone_configs')
    op.drop_table('zone_configs')
    # ### end Alembic commands ###
